---
abstract: 'Extract useful metadata from HTML.'
author:
  - 'Tore Aursand <toreau@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.64
  File::Slurp: 9999.19
  FindBin: 1.42
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-ExtractMeta
requires:
  Mojolicious: 3.84
  Mouse: 1.05
version: 0.09
