---
abstract: 'Extract meta data from HTML.'
author:
  - 'Tore Aursand <toreau@gmail.com>'
build_requires:
  File::Slurp: 0
  FindBin: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-ExtractMeta
requires:
  Mojo::DOM: 0
  Mojo::Util: 0
  Moose: 0
version: 0.02
