---
abstract: 'Extract metadata from HTML.'
author:
  - 'Tore Aursand <toreau@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-ExtractMeta
requires:
  File::Slurp: 9999.19
  FindBin: 1.42
  Mojolicious: 3.69
  Moose: 2.0604
  Test::More: 0.98
version: 0.05
